site_name: BrowserWrapper Documentation
site_description: 'Documentation for BrowserWrapper'
site_author: 'Michael Fessenden'
docs_dir: docs/
repo_name: 'MikeFez/BrowserWrapper'
repo_url: 'https://github.com/MikeFez/BrowserWrapper'
nav:
    - Home: Index.md
    - BrowserWrapper Functionality: BrowserWrapper.md
    - BrowserWrapperConfiguration: BrowserWrapperConfiguration.md
theme:
  name: 'material'

plugins:
  - mkdocstrings
  - search