site_name: Test docs
site_description: 'A docs test'
site_author: 'Michael Fessenden'
docs_dir: docs/
repo_name: 'MikeFez/BrowserWrapper'
repo_url: 'https://github.com/MikeFez/BrowserWrapper'
nav:
    - Home: index.md
theme:
  name: 'material'

plugins:
  - mkdocstrings