site_name: BrowserWrapper Documentation
site_description: 'Documentation for BrowserWrapper'
site_author: 'Michael Fessenden'
docs_dir: .
repo_name: 'MikeFez/BrowserWrapper'
repo_url: 'https://github.com/MikeFez/BrowserWrapper'
nav:
    - Home: README.md
    - BrowserWrapper Functionality: docs/BrowserWrapper.md
    - BrowserWrapperConfiguration: docs/BrowserWrapperConfiguration.md
theme:
  name: 'material'

plugins:
  - mkdocstrings
  - search